# Aspectos básicos de algebra

Antes algunos conceptos básicos de python. Para ello se utilizará la libreria de **Numpy**, esta libreria funciona como cualquier otra libreria en paquetes estadísticos, por ejemplo R.

Sin embargo, Python tiene sus particularidades. Para instalar la libreria, primero se debe ir al *cmd* de Windows y digitar
*python -m pip install numpy --user*. La última parte, *--user* se hace para evitar problemas de permisos cuando no se es Administrador. Una vez ejecutado, el paquete se instalará solo para el usuario.

Luego, para cargar la libreria se ejecuta el siguiente comando:

In [10]:
import numpy as np  # carga todas las funciones que tiene la libreria, distinto sería usar el comando from
                    # la parte 'as' indica la denominación que va a tener la libreria en el código

## 1. Vectores

Un vector se define como un objeto que contiene una cierta cantidad de elementos. Por ejemplo, sea un vector $a$ cuyos elementos sean $1,2,3,4$.

Si los elementos se disponen o se arreglan en fila, se dice que el vector $a$ es un vector fila cuyas dimensiones serían $(1,4)$ dado que tendria $1$ fila y $4$ columnas. En python escribimos este vector de la forma:

In [27]:
# create a vector
a = np.array([1, 2, 3, 4])
print(a)
a.shape # dimensiones del vector a

[1 2 3 4]


(4,)

En la práctica, en estos tipos de programas da lo mismo si es un vecto fila o un vector columna. Lo importante es que sea un vector.

Ahora, algunos *tips* sobre los vectores, sus elementos y como hacer operaciones entre ellos.

### 1.1. Elementos de un vector

En cualquier programa estadístico cuando se crea un vector se genera un *índice* que indica la posición del elemento. En particular, Python inicia el *índice* en cero, es decir, el primer elemento de un vecto se accede diciendo a Python que queremos el elemento cuyo índice sea cero.

Para el ejemplo, anterior si deseamos el primer elemento de $a$ entonces:

In [28]:
a[0]

1

A su vez es posible hacer operaciones entre elementos del vector. Por ejemplo, si se desea sumar el elemento cuyo *índice* es 2 y el elemento cuyo *índice* es 3 se debe ejecutar:

In [29]:
a[2]+a[3]

7

Fijemonos que el programa sumó $3+4$, por qué? Recuerde que Python inicia el *índice* en cero y por lo tanto $a[2]$ y $a[3]$ corresponden a los elementos 3 y 4 respectivamente.

### 1.2. Operaciones con vectores

Cuando se realizan operaciones con vectores es necesario tener en cuenta que en este tipo de paquetes existe una diferenciación importante.

Por una parte, se tiene operaciones *element-wise* que consiste en que la operación a realizar se "aplica" a cada elemento del vector. Por ejemplo, al sumar dos vectores se está realizando una operación *element-wise* en la medida que se está sumando el primer elemento de un vector con el primer elemento de otro vector, el segundo con el segundo, etc.

Por otra parte, se tiene operaciones "entre objetos" es decir operaciones que se aplican sobre todo el vector. El ejemplo más claro de este tipo de operaciones es la diferencia entre la multiplicación "normal" y el producto punto.

#### 1.2.1 Element-wise

Creemos otro vector, esta vez llamemolo $b$ y cuyos elementos sean $5, 6, 7, 8$.

In [30]:
b = np.array([5, 6 , 7, 8])

Ahora, veamos como funciona la suma:

In [31]:
c = a + b
print(c)

[ 6  8 10 12]


Notemos que es el mismo resultado que realizar:

In [32]:
np.array([a[0]+b[0], a[1]+b[1], a[2]+b[2], a[3]+b[3]])

array([ 6,  8, 10, 12])

La resta funciona de la misma forma:

In [33]:
d = a - b
print(d)

[-4 -4 -4 -4]


La multiplicación:

In [34]:
e = a*b
print(e)

[ 5 12 21 32]


La división:

In [35]:
f = b/a
print(f)

[5.         3.         2.33333333 2.        ]


#### 1.2.2. Operaciones con vectores como objeto

Como se mencionó, en este tipo de operaciones la operación hace referencia a todo el vector.

Producto Punto:

In [36]:
g = a.dot(b)
print(g)

70


Cuál es la diferencia entre la multiplicación y el producto punto? 
Escriba una línea de comando que replique lo hecho por la función *.dot()*

## 2. Matrices

Las matrices son objetos que están disñados en filas y columnas. Por ejemplo, sea una matriz:

$$A=\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$$

Esta matriz tiene dimensiones $(3,3)$ y se dice que es cuadrada dado que el número de filas es igual al número de columnas.

Ahora, creeemos la matriz con código en Python:

In [46]:
A = np.matrix([[1,2,1],[3,0,1],[0,2,4]])
print(A)

[[1 2 1]
 [3 0 1]
 [0 2 4]]


Cree la siguiente matriz:

$$B=\begin{bmatrix} 3 & 7 & 1 \\ 6 & 4 & 2 \\ 5 & 0 & 4 \end{bmatrix}$$

In [47]:
B = np.matrix([[3,7,1],[6,4,2],[5,0,4]])
print(B)

[[3 7 1]
 [6 4 2]
 [5 0 4]]
