# Aspectos básicos de algebra

Antes algunos conceptos básicos de python. Para ello se utilizará la libreria de **Numpy**, esta libreria funciona como cualquier otra libreria en paquetes estadísticos, por ejemplo R.

Sin embargo, Python tiene sus particularidades. Para instalar la libreria, primero se debe ir al *cmd* de Windows y digitar
*python -m pip install numpy --user*. La última parte, *--user* se hace para evitar problemas de permisos cuando no se es Administrador. Una vez ejecutado, el paquete se instalará solo para el usuario.

Luego, para cargar la libreria se ejecuta el siguiente comando:

In [5]:
import numpy as np  # carga todas las funciones que tiene la libreria, distinto sería usar el comando from
                    # la parte 'as' indica la denominación que va a tener la libreria en el código

## 1. Vectores

Un vector se define como un objeto que contiene una cierta cantidad de elementos. Por ejemplo, sea un vector $a$ cuyos elementos sean $1,2,3,4$.

Si los elementos se disponen o se arreglan en fila, se dice que el vector $a$ es un vector fila cuyas dimensiones serían $(1,4)$ dado que tendria $1$ fila y $4$ columnas. En python escribimos este vector de la forma:

In [6]:
# create a vector
a = np.array([1, 2, 3, 4])
print(a)
a.shape # dimensiones del vector a

[1 2 3 4]


(4,)

En la práctica, en estos tipos de programas da lo mismo si es un vecto fila o un vector columna. Lo importante es que sea un vector.

Ahora, algunos *tips* sobre los vectores, sus elementos y como hacer operaciones entre ellos.

### 1.1. Elementos de un vector

En cualquier programa estadístico cuando se crea un vector se genera un *índice* que indica la posición del elemento. En particular, Python inicia el *índice* en cero, es decir, el primer elemento de un vecto se accede diciendo a Python que queremos el elemento cuyo índice sea cero.

Para el ejemplo, anterior si deseamos el primer elemento de $a$ entonces:

In [7]:
a[0]

1

A su vez es posible hacer operaciones entre elementos del vector. Por ejemplo, si se desea sumar el elemento cuyo *índice* es 2 y el elemento cuyo *índice* es 3 se debe ejecutar:

In [8]:
a[2]+a[3]

7

Fijemonos que el programa sumó $3+4$, por qué? Recuerde que Python inicia el *índice* en cero y por lo tanto $a[2]$ y $a[3]$ corresponden a los elementos 3 y 4 respectivamente.

### 1.2. Operaciones con vectores

Cuando se realizan operaciones con vectores es necesario tener en cuenta que en este tipo de paquetes existe una diferenciación importante.

Por una parte, se tiene operaciones *element-wise* que consiste en que la operación a realizar se "aplica" a cada elemento del vector. Por ejemplo, al sumar dos vectores se está realizando una operación *element-wise* en la medida que se está sumando el primer elemento de un vector con el primer elemento de otro vector, el segundo con el segundo, etc.

Por otra parte, se tiene operaciones "entre objetos" es decir operaciones que se aplican sobre todo el vector. El ejemplo más claro de este tipo de operaciones es la diferencia entre la multiplicación "normal" y el producto punto.

#### 1.2.1 Element-wise

Creemos otro vector, esta vez llamemolo $b$ y cuyos elementos sean $5, 6, 7, 8$.

In [9]:
b = np.array([5, 6 , 7, 8])

Ahora, veamos como funciona la suma:

In [10]:
c = a + b
print(c)

[ 6  8 10 12]


Notemos que es el mismo resultado que realizar:

In [11]:
np.array([a[0]+b[0], a[1]+b[1], a[2]+b[2], a[3]+b[3]])

array([ 6,  8, 10, 12])

La resta funciona de la misma forma:

In [12]:
d = a - b
print(d)

[-4 -4 -4 -4]


La multiplicación:

In [13]:
e = a*b
print(e)

[ 5 12 21 32]


La división:

In [14]:
f = b/a
print(f)

[5.         3.         2.33333333 2.        ]


#### 1.2.2. Operaciones con vectores como objeto

Como se mencionó, en este tipo de operaciones la operación hace referencia a todo el vector.

Producto Punto:

In [15]:
g = a.dot(b)
print(g)

70


Cuál es la diferencia entre la multiplicación y el producto punto? 
Escriba una línea de comando que replique lo hecho por la función *.dot()*

## 2. Matrices

Las matrices son objetos que están disñados en filas y columnas. Por ejemplo, sea una matriz:

$$A=\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$$

Esta matriz tiene dimensiones $(3,3)$ y se dice que es cuadrada dado que el número de filas es igual al número de columnas.

Ahora, creemos la matriz con código en Python:

In [16]:
A = np.matrix([[1,2,1],[3,0,1],[0,2,4]])
print(A)
A.shape # dimensiones de la matriz

[[1 2 1]
 [3 0 1]
 [0 2 4]]


(3, 3)

Cree la siguiente matriz y determine sus dimensiones:

$$B=\begin{bmatrix} 3 & 7 & 1 \\ 6 & 4 & 2 \\ 5 & 0 & 4 \end{bmatrix}$$

In [17]:
B = np.matrix([[3,7,1],[6,4,2],[5,0,4]])
print(B)
B.shape

[[3 7 1]
 [6 4 2]
 [5 0 4]]


(3, 3)

### 2.1. Elementos de una matriz

Al igual que se hizo con vectores, con las matrices también podemos acceder a sus elementos. En este caso, debemos tener presente que existen dos *índices*, uno para las filas y uno para las columnas.

Por lo tanto, si deseamos acceder al primer elemento de la matriz, es decir, al elemento ubicado en la primera fila y en la primera columna debemos ejecutar:

In [18]:
A[0,0]

1

Acceda a los siguientes elementos:

1. Segunda fila y tercera columna de A.
2. Tercera fila y segunda columna de B.
3. Primera fila y segunda columna de B.

In [19]:
# 1. Segunda fila y tercera columna de A
A[1,2]

1

In [20]:
# 2. Tercera fila y segunda columna de B
B[2,1]

0

In [21]:
# 3. Primera fila y segunda columna de B
B[0,1]

7

## 2.2. Operaciones con matrices

De igual forma, debemos diferenciar entre las *element-wise* y aquellas sobre los objetos completos

### 2.2.1 Element-wise

Suma:

In [22]:
C = A+B
print(C)

[[4 9 2]
 [9 4 3]
 [5 2 8]]


Resta:

In [23]:
D = A-B
print(D)

[[-2 -5  0]
 [-3 -4 -1]
 [-5  2  0]]


Multiplicación:

In [24]:
E = A*B
print(E)

[[20 15  9]
 [14 21  7]
 [32  8 20]]


Qué pasó? Si hacemos la multiplicación a mano del primer elemento de $A$ con el primer elemento de $B$ obtenemos:

In [25]:
A[0,0]*B[0,0]

3

Pero el primer elemento de la matriz $E$ es 20. Entonces, qué operación hizo Pyhton? Y cómo obtenemos el resultado que queremos (*element-wise*)?

Primero, qué operación hizo Python? Fijemonoso que ambas matrices son de $3x3$ así Python interpreta que estamos haciendo un **producto cruzado** entre matrices. Por ejemplo, el primer elemento de $E$ resulta de la siguiente operación:

$E_{1,1} = A_{1,1}*B_{1,1}+A_{1,2}*B_{2,1}+A_{1,3}*B_{3,1}$

En código sería:

In [26]:
A[0,0]*B[0,0]+A[0,1]*B[1,0]+A[0,2]*B[2,0]

20

Segundo, cómo obtenemos el resultado que queremos? Para ello es necesario utilizar una función. Es decir:

In [27]:
np.multiply(A,B)

matrix([[ 3, 14,  1],
        [18,  0,  2],
        [ 0,  0, 16]])

Ahora sí tenemos la multiplicación elemento por elemento.

División:



In [28]:
F = A/B
print(F)

[[0.33333333 0.28571429 1.        ]
 [0.5        0.         0.5       ]
 [0.                inf 1.        ]]


C:\Program Files (x86)\Python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


### 2.2.2. Operaciones de matrices como objetos

Como ya se mencionó, la múltiplicación usando el simbolo * realiza el producto punto.
Sin embargo, es necesario tener en cuenta que a diferencia de multiplicar número al multiplicar matrices el orden importa.

Por ejemplo,

In [29]:
print(A*B)
print(B*A)

[[20 15  9]
 [14 21  7]
 [32  8 20]]
[[24  8 14]
 [18 16 18]
 [ 5 18 21]]


Los resultados son diferentes, por qué?

## 2.3. Algunas operaciones y comandos con matrices

### 2.3.1 Inversa de una matriz

Así como en número se tiene un inverso, por ejemplo para $x=2$ su inverso multiplicativo sería $1/x=1/2$, en la matrices ocurre lo mismo.

Cumpliendo ciertas condiciones es posible calcular la inversa de una matriz. Las condiciones son básicamente que exista "independencia" entre las filas y columnas de la matriz. En palabras más simple, "independecia" se refiere a que no es posible expresar una fila o columna en función de otra.

Por ejemplo considere la matriz:

$$C=\begin{bmatrix} 1 & 2 \\ 2 & 4 \end{bmatrix}$$

Es posible expresar una fila en función de la otra? La respuesta es sí, vea que la segunda fila es la primera multiplicada por $2$.

Construyamos la matriz $C$ y hallemos la inversa.


In [34]:
C = np.matrix([[1,2],[2,4]])
print(C)
np.linalg.inv(C)

[[1 2]
 [2 4]]


LinAlgError: Singular matrix

Salió un error que dice "Singular matrix", lo que tecnicamente signfica que el determinante es cero o simplemente que no es posible invertirla.

Ahora, calcule el inverso de la matriz $B$ creada anteriormente.

In [35]:
np.linalg.inv(B)

matrix([[-0.22857143,  0.4       , -0.14285714],
        [ 0.2       , -0.1       ,  0.        ],
        [ 0.28571429, -0.5       ,  0.42857143]])

### 2.3.2 Matriz identidad

La matriz identidad es aquella cuyos elementos de la diagonal son $1$ y el resto es $0$. Además, la mtriz identidad es cuadrada es decir que el número de filas es igual al número de columnas.

En particular, suponga que deseamos crear una matriz identidad de $(3x3)$ de la forma:

$$I=\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$

El código sería:

In [30]:
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Qué pasa si multiplicamos una matriz como $A$ por la matriz $I$?

In [31]:
print(A*I)
print(I*A)

[[1. 2. 1.]
 [3. 0. 1.]
 [0. 2. 4.]]
[[1. 2. 1.]
 [3. 0. 1.]
 [0. 2. 4.]]


Da como resultado la misma matriz $A$ no importa si está a la derecha o la izquierda la matriz $I$.

Ok, entonces para qué sirve la matriz identidad? Es util es pruebas que involucran algerba líneal y en ocasiones pueden facilitar los cálculos en un operación.

Finalmente, la inversa de una matriz y la identidad tienen relación. En general, se cumple que:

$A*A^{-1} = I$

Para cualquier matriz $A$ que tenga una inversa.

Ahora, mostremolo con la matriz $B$ y su inversa


In [36]:
B*np.linalg.inv(B)

matrix([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 2.22044605e-16, 1.00000000e+00]])